data:
  neg_count: 1
  low_rating_thres: ~
  binarized_rating_thres: 3.0
  min_user_inter: 10
  min_item_inter: 10

train:
  lambda_theta: 1e-7
  lambda_beta: 1e-7
  truncation: 1

eval:
  method: conditional # conditional / marginal